kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker/whalesay
  commands:
  - cowsay \"5 mana. Teferi.\" by Matsuoka

trigger:
  branch:
  - master
  event:
  - push
  - pull_request
  - tag
  - promote
  - rollback
  repo:
  - cs-sayo/test-react-drone